name: CodeCov

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]  # latest release minus two
        requirements-file: [
            dj42_cms311.txt,
            dj42_cms41.txt,
            dj50_cms41.txt,
            dj51_cms41.txt,
            dj52_cms50.txt,
            dj60_cms50.txt,
        ]
        os: [
            ubuntu-latest,
        ]
        exclude:
          # Python 3.14 only works with Django 5.2+
          - python-version: "3.14"
            requirements-file: dj42_cms311.txt
          - python-version: "3.14"
            requirements-file: dj42_cms41.txt
          - python-version: "3.14"
            requirements-file: dj50_cms41.txt
          - python-version: "3.14"
            requirements-file: dj51_cms41.txt
          # Python 3.10 and 3.11 only supported until Django 5.2
          - python-version: "3.10"
            requirements-file: dj60_cms50.txt
          - python-version: "3.11"
            requirements-file: dj60_cms50.txt
          # Python 3.12 and 3.13 don't support Django 4.2 with CMS 3.11
          - python-version: "3.12"
            requirements-file: dj42_cms311.txt
          - python-version: "3.13"
            requirements-file: dj42_cms311.txt

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: '2'

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip uv
        uv pip install --system -r tests/requirements/${{ matrix.requirements-file }}
    - name: Run coverage
      run: |
        coverage run -m pytest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v5
